### ISSUE TITLE
Make map view show heavier lines for more flown routes

### ISSUE THREAD

**Issue by bigmak40** [pbogre/jetlog#10]
On the map view, make the line for routes thicker if a route is more heavily used.

**Comment by pbogre** [comment]
Good idea, I will look into this.

**Comment by pbogre** [comment]
The way this change has been implemented is that the lines / markers start at the default widths of `1` and `3` respectively, and for every 3 flights / airport visits their width increases by 1, capped at 6 for lines and 12 for markers.
