### ISSUE TITLE
Support flights longer than 24 hours

### ISSUE THREAD

**Issue by pbogre** [pbogre/jetlog#13]
Currently if a flight is longer than 24 hours, it counts the difference in times as if they were the same day (i.e. when arrival time > departure time).

Perhaps add a checkbox that says the arrival was on the following day?

**Comment by pbogre** [comment]
Closing this because... 24+ hour flights shouldn't be possible, right?

**Comment by adepssimius** [comment]
Maybe it is possible? Consider an ATL to SYD flight that gets diverted to HNL and has to sit there for 10 hours while parts are flown in and repairs are made then continues. Is that counted as flight time? Is that the same flight number?

**Comment by pbogre** [comment]
I'd say those would be two separate flights. When you have a connection, the two flights have different starting and ending points, and also it allows you to mark the connection airport as visited.

**Comment by adepssimius** [comment]
I don't have an example, but I assume since you pull in from FR24 something like that would be represented somehow in their API, no? Mostly I'm asking if your source data would see it as two separate flights.

**Comment by adepssimius** [comment]
I'm also not talking about a connection. When a plane has an IROP and stops for fuel/mechanical/medical emergency at an unplanned station then the flight number isn't typically changed when they continue. I'm unsure how FR24 would handle that.

**Comment by pbogre** [comment]
Oh I see what you mean now.

I'm not sure what you mean by 'source data' or 'pull in from FR24', because currently i'm not pulling flight data from anywhere (that's just an enhancement that I plan for the future), currently all the information you provide is taken as true, even if the route doesn't actually exist.

Anyway, flights longer than 24h are possible now, thanks to the new `arrival_date` field introduced for issue #31
