### ISSUE TITLE
Allow switch between Imperial measurement system and Metric measurement system

### ISSUE THREAD

**Issue by PaPaTheGMan** [pbogre/jetlog#14]
It would be nice to be able to show distances in either kilometers or miles.

**Comment by pbogre** [comment]
Somehow I hadn't thought of that. Thanks for the issue, I'll look into this.

**Comment by matjako** [comment]
If I can steal the issue: Is it also possible to add option to allow changing between 12h and 24h clock - 17:00 instead of 5:00 PM etc?

**Comment by pbogre** [comment]
> If I can steal the issue: Is it also possible to add option to allow changing between 12h and 24h clock - 17:00 instead of 5:00 PM etc?

I have opened an issue for that, #15

**Comment by pbogre** [comment]
This has been implemented in the latest commit. I'll upload the new experimental docker image, let me know how it goes :)

**Comment by PaPaTheGMan** [comment]
Awesome, work perfect!!  Thank you!

**Comment by pbogre** [comment]
For other people looking at this, these changes are now part of the latest stable (tag `:latest`) docker image
