### ISSUE TITLE
Move documentation to github wiki

### ISSUE THREAD

**Issue by pbogre** [pbogre/jetlog#23]
For better organization and less clutter in the README, move technical documentation (docker, environment variables, importing options, API, ...) to dedicated Github Wiki pages.

**Comment by vnl** [comment]
Happy to help here.

Might I add that you have done fantastic work. I have been looking for this kind of application.

**Comment by pbogre** [comment]
Awesome that you'd like to help. I'm not sure how to allow others to create Wiki pages on my repo, do I need to give you any special permission?

Also, thanks for liking the project! I didn't expect it to blow up this much 😅

**Comment by vnl** [comment]
Oh btw you can provide permission to collaborate just for the Wiki I think : https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

You have no idea; I have researched this on Reddit and places for over two years. 
There are some beautiful geocharts out there. I like self-hosted and was looking for inspiration from https://flightmapper.io/ and https://www.logmytrip.net/

**Comment by pbogre** [comment]
I have enabled editing of Wiki pages. Is that only for editing, or are you also allowed to create the Wiki pages? I could create some of them to allow you to edit them.

Wow, yeah I remember looking for something like this project and being shocked at finding absolutely no self-hostable solution. Of course, I decided to make my own. Those services you mention are quite nice, could take some inspiration from them.

**Comment by vnl** [comment]
I am going to try to create a sample page and see if I have permissions

**Comment by pbogre** [comment]
I see that you've added some pages to the Wiki, thanks for the contribution!

I have some feedback. Firstly, my idea of the Wiki is to provide more in-depth and technical specifications than the README, so for instance pages like `Home`, `Features`, `Tech Stack and Credits` aren't really needed. (I see that you were pretty much re-writing the readme to fit in the Wiki, and I didn't make it clear in the issue description what I wanted the wiki to be).

Since I don't expect you to look up all the technical aspects of the Wiki from the code to write these docs, all I need help with is setting up the formatting and the pages. Here's what I would like, some of which you've already done:

Page: `Installation`
Sections: `Docker`, `Manual`
For each of these sections, you can just copy paste from the readme 

Page: `Usage`
Sections: `Home`, `New flight`, `All flights`, `Statistics`, `Settings`
Leave these empty

Page: `Importing`
Sections: `MyFlightRadar24`, `Custom CSV`
Copy paste from readme

Page: `Exporting`
Sections: `CSV`, `iCal`
Leave these empty


At some point I'll get around to writing all the technical details for these, but for now the templates are sufficient. Thanks for the help :)

**Comment by vnl** [comment]
@pbogre Of course, this was only a test to see that I can get it done. 
I will start working on the suggestions you gave.
