### ISSUE TITLE
Add option to record flights for more than one user

### ISSUE THREAD

**Issue by adepssimius** [pbogre/jetlog#26]
it would be nice to be able to mark that one of my kids or my wife took a flight as well, or even proper user account support (think OIDC, not local auth).

not that I'm ungrateful for this awesome tracking tool already, I'm just listing off my "this would be nice" list since I share the passion for data tracking and aviation :)

**Comment by joel72265** [comment]
I too think this would be a wonderful feature to have

**Comment by cprpolo** [comment]
Congratulations for the project!! :) 

And I agree! 
It may be okay for a single user but the basic authentication i think is a must, i would like this expose this to the internet via traefik and Authentication is needed if i don't set it in traefik.

Looking forward for this to progress :)

**Comment by simonpt** [comment]
+1 for at least basic auth or even a password while still single user. Just in case someone on the local network stumbles upon on it and messes with my hard work :)

**Comment by pbogre** [comment]
Since user authentication is so requested here, and because it is different from the ability to have multiple users, I have opened an issue for that specifically, which you can see above.

**Comment by pbogre** [comment]
For anyone interested in this issue, a working image is available with the `:experimental` tag. I am going to do some tests on that image before I release it, hopefully soon. Sorry for the long wait 🙂
