### ISSUE TITLE
Build docker container for ARM processors

### ISSUE THREAD

**Issue by benjaminjonard** [pbogre/jetlog#29]
Hello, first of all thanks for this software, I really like it. 

Would it be possible to add compatibility with ARM processors ? It would be nice to be able to run jetlog on a raspberry pi for example

**Comment by pbogre** [comment]
I'm glad you're enjoying the project.

This shouldn't be a complicated addition, I just need to add `linux/arm64` to the `--platforms` option when building the docker image. I'll test this soon 

[Docker docs](https://docs.docker.com/build/building/multi-platform/#building-multi-platform-images)

I wonder if this will affect the size of the downloaded image?

**Comment by benjaminjonard** [comment]
Thanks 👍 

It will create 2 different images for a each tag, so it won't impact the original image size. (when using `docker run` or `docker compose up`, Docker will guess which image to use based on the machine architecture)

**Comment by adepssimius** [comment]
> I'm glad you're enjoying the project.
> 
> This shouldn't be a complicated addition, I just need to add `linux/arm64` to the `--platforms` option when building the docker image. I'll test this soon
> 
> [Docker docs](https://docs.docker.com/build/building/multi-platform/#building-multi-platform-images)
> 
> I wonder if this will affect the size of the downloaded image?

This would not affect the size of the downloaded image. There are two distinct images for two different architectures. By making both available, only the image for the correct architecture is pulled.

**Comment by pbogre** [comment]
After building the image with the following command:

```sh
docker buildx build -t pbogre/jetlog:experimental -f Dockerfile . --platform=linux/amd64,linux/arm64
```

The image with `:experimental` tag should be available for both platforms. I will change this to `:latest` when there has been enough testing.

**Comment by benjaminjonard** [comment]
I tested tested the experimental image on a Raspberry Pi and another arm device and it works great. Thanks !
