### ISSUE TITLE
Add ability to set arrival time +1 day/+2 days etc.

### ISSUE THREAD

**Issue by nirenjan** [pbogre/jetlog#31]
If the user is taking a long flight (trans-Atlantic or trans-Pacific), it is possible to have a long flight time of 15+ hours, effectively landing at the destination airport at a time that is actually the next day. However, the default client assumes that it is on the same day, and results in a short duration by default. An option with +1 day, +2 days or -1 days would be great to have so that the client can correctly update the duration without the user having to manually enter it.

**Comment by pbogre** [comment]
The latest commits create a new field `arrival_date`, and allow you to set it when creating a flight.

It is an optional field. This means that if you choose not to set it, then calculating the duration will be handled the same way as previously (difference between times, and if arrival time < departure time then assume 1 day difference). If you choose to set it and not set the times, then duration will not be calculated. If you set both this field and the times, then the duration will be calculated taking into account the arrival date. 

Let me know if you encounter any problems with this commit, and if this solves your issue. I see this as a fix for #32 as well.
