### ISSUE TITLE
CSV export issues

### ISSUE THREAD

**Issue by simonpt** [pbogre/jetlog#36]
Thanks for adding the CSV export feature.

Noticed a couple of issues:

1. The export filename contains quotation marks:

`"jetlog.csv"`

2. The export is limited to 50 flights. Changing the filter setting in All Flights makes no difference.

**Comment by pbogre** [comment]
Thanks for finding these bugs, I'll work on this as soon as I get back home (end of august)

**Comment by pbogre** [comment]
@simonpt The commits shown above should fix these problems, so I'm going to close this issue for now. If you are still encountering these bugs, please reopen this issue.
