### ISSUE TITLE
Jetlog doesn't seem timezone aware

### ISSUE THREAD

**Issue by jamess60** [pbogre/jetlog#38]
I have a 4900 mile flight with a 270 min duration (as I went back in time -6). The return flight on the same route shows 935 minute duration (because I went forward in time). 

Ideally, JetLog needs to know the timezone of each airport so it can factor the adjustment into durations

**Comment by pbogre** [comment]
duplicate of #32

**Comment by jamess60** [comment]
Apologies, will update there
