### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by pbogre** [pbogre/jetlog#43]
Add the ability to set a user name and password which would then be required to access Jetlog through a custom login page.

Required for #26

**Comment by EM-Tom** [comment]
Love this project - I'd like to see an admin password to allow write access, but able to share read access publicy with no auth.

**Comment by cprpolo** [comment]
As @EM-Tom said! 
Admin write access will be great, read access i prefer to also have it per user but I understand it may be harder :)

**Comment by pbogre** [comment]
@EM-Tom @cprpolo I hear your feedback and I agree that it would be a useful addition to Jetlog.

Once I implement authentication via username/password, I will probably work towards a read-only user, and the latter feature is not too far off from the former.

**Comment by cprpolo** [comment]
Great!!! Wish I could help :)

**Comment by DevGoran** [comment]
@pbogre is Oauth also on your radar? Would love to have automatic user creation through authentik as well.

**Comment by pbogre** [comment]
For anyone interested in this issue, a working image is available with the `:experimental` tag. I am going to do some tests on that image before I release it, hopefully soon. Sorry for the long wait 🙂
