### ISSUE TITLE
Add tags to Docker images

### ISSUE THREAD

**Issue by thomas-mc-work** [pbogre/jetlog#44]
… so you can choose a specific version for the Docker image from Docker hub. Thanks!

**Comment by pbogre** [comment]
I currently have the `:latest` and `:experimental` tags on docker hub, which provide stable and unstable releases respectively.

Do you mean that I should have a tag for each version, e.g. `:1.0.0-beta`, `:1.0.0`, ...? That could be done

**Comment by thomas-mc-work** [comment]
> Do you mean that I should have a tag for each version, e.g. `:1.0.0-beta`, `:1.0.0`, ...? That could be done

Exactly. Thanks in advance!

**Comment by pbogre** [comment]
@thomas-mc-work I just pushed an image for version 1.0.0, which you can pull using `pbogre/jetlog:1.0.0`. I won't make one for the beta version, but from now on I'll remember to push an image for each new version.
