### ISSUE TITLE
Record class

### ISSUE THREAD

**Issue by EM-Tom** [pbogre/jetlog#45]
Enhancement request:

Record class of flight 

Economy
Premium Economy
Business
First 

Thank you !

**Comment by pbogre** [comment]
Thanks for the feature request. This shouldn't be hard to implement👍

**Comment by pbogre** [comment]
@EM-Tom this feature was implemented in the latest commits. You can test it out by pulling the `:experimental` tag, and let me know if you encounter any problems by reopening this issue

**Comment by EM-Tom** [comment]
Love it - thanks.
