### ISSUE TITLE
Edit exsting flight: all field empty

### ISSUE THREAD

**Issue by thomas-mc-work** [pbogre/jetlog#52]
Since version `1.0.2` I only see an empty form when editing an existing flight:

![image](https://github.com/user-attachments/assets/c54613d8-9c1a-45fe-bf26-e9a3199b369f)

**Comment by pbogre** [comment]
Was this not the case for you in previous versions? From what i've tested, the edit page has always been empty values, and only the data that you insert is sent to update the flight. I do think this could be changed to be better from a UX standpoint, though.

**Comment by thomas-mc-work** [comment]
> Was this not the case for you in previous versions?

I cannot rule out the possibility, though I also couldn't find it: <https://github.com/pbogre/jetlog/issues?q=sort%3Aupdated-desc+is%3Aissue+author%3Athomas-mc-work+is%3Aopen>

> I do think this could be changed to be better from a UX standpoint, though.

That would be nice. But good to know how it is working currently. Thanks!
