### ISSUE TITLE
Enter flight values as placeholders on Edit page

### ISSUE THREAD

**Issue by moshobo** [pbogre/jetlog#55]
When I am editing a flight, I want to see the existing field values so that I know what I am changing.

Ideally, this information is entered as a placeholder value, so that visually I can distinguish what is already saved vs. new information I've entered.

**Comment by pbogre** [comment]
Thanks for opening an issue about this, and I agree that this is a good idea, I can't quite remember why I didn't implement it in the first place.

I don't think it should be too hard to implement, so I'll work on it soon.

**Comment by pbogre** [comment]
This issue has been fixed. If you encounter any problems, feel free to reopen. Note that it is currently only available with the `experimental` docker tag.
