### ISSUE TITLE
Update password hashing to argon2 instead of bcrypt

### ISSUE THREAD

**Issue by adepssimius** [pbogre/jetlog#60]
I don't think bcrypt is considered best practice anymore. Before you release with auth, consider switching out to argon2 hashing instead. I'm happy to contribute a PR as well in a week or so.

**Comment by pbogre** [comment]
Looks like you're still running the version that used bcrypt. Are you sure you pulled the latest image?

**Comment by adepssimius** [comment]
You were exactly right. It was still cached. It started on the same node and I wasn't aware of this nuance to using a tag other than `:latest`.

> If the image tag is :latest, the imagePullPolicy will be automatically set to Always.
