### ISSUE TITLE
[Enhancement/Discussion] World map UI update 

### ISSUE THREAD

**Issue by vnl** [pbogre/jetlog#68]
I thought I would open this issue to discuss UI enhancements regarding maps. 

One option I could see with very little research—I know there may be others—is Mapbox GL JS. 
I see a healthy free option there, but it may be an option for BYOK. 

(I do personally use Flighty now - previously App In The Air - so was getting map ideas)

**Comment by pbogre** [comment]
Do you mean to use a different map library than `react-world-maps`? Is there a reason why this change is worth making?

**Comment by vnl** [comment]
I honestly thought certain types of maps are not possible with `react-world-maps` 
Now that I look for examples, I believe changing the library is not required. 
Globe I was after: https://codesandbox.io/p/sandbox/react-simple-map-rotating-globe-vb2l1

**Comment by pbogre** [comment]
Ah I see what you mean now. I'll close this issue since it's been resolved I guess, however if you feel that some more UI elements should be created with the map, feel free to open an issue for that.
